name: CI/CD ML Pipeline

on:
  push:
    branches:
      - dev
      - prod

env:
  AWS_REGION: us-east-2                  
  BUCKET_NAME: mi-proyecto-salud-mental-mlops
  AWS_ROLE_ARN: arn:aws:iam::522412052494:role/GitHubActionsWorkflowRole

 # REQUERIMIENTO CRÍTICO DE GITHUB PARA OIDC:
permissions:
  id-token: write
  contents: read

jobs:
  extract-env:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set-env.outputs.env_name }}
    steps:
      - id: set-env
        run: |
          if [ "${{ github.ref_name }}" = "prod" ]; then
            echo "env_name=prod" >> $GITHUB_OUTPUT
          else
            echo "env_name=dev" >> $GITHUB_OUTPUT
          fi

  test:
    needs: extract-env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Test Dependencies
        run: |
          pip install pytest onnxruntime numpy pandas boto3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

     # REQUERIMIENTO: Descargar el modelo y los datos desde S3 en las etapas de CI/CD
      - name: Download Model and Test Data from S3 Bucket
        run: |
          aws s3 cp s3://${{ env.BUCKET_NAME }}/modelos/${{ needs.extract-env.outputs.env_name }}/mental_health_model.onnx mental_health_model.onnx
          aws s3 cp s3://${{ env.BUCKET_NAME }}/datos/test_data.csv test_data.csv

      # REQUERIMIENTO: Ejecución de las pruebas unitarias especificadas
      - name: Run Unit Tests
        run: |
          pytest tests/test_model.py -v

  build-promote:
    name: Build, Tag, and Push Image to Amazon ECR
    needs: [extract-env, unit-tests] # Revisa que dependa de tus jobs anteriores
    runs-on: ubuntu-latest
    
    # ¡ESTO ES LO QUE FALTA! Permite que este Job use el token OIDC para asumir el rol en AWS
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1